package com.epy.linespotv2.domain.model.riwayat

data class DetilParkirResponseModel(
    val tanggal: String,
    val transactionId: Long,
    val transactionCode: String,
    val sessionId: Long,
    val plateNumber: String,
    val vehicleTypeId: Long,
    val vehicleTypeCode: String,
    val vehicleTypeName: String,
    val paymentMethodId: Long,
    val paymentMethodCode: String,
    val paymentMethodName: String,
    val locationId: Long,
    val locationName: String,
    val locationAddress: String,
    val areaId: Long? = null,
    val areaName: String? = null,
    val zoneId: Long? = null,
    val zoneName: String? = null,
    val baseAmount: Long,
    val discountAmount: Long,
    val finalAmount: Long,
    val companyShare: Long,
    val jukirShare: Long,
    val taxAmount: Long,
    val feeAmount: Long,
    val transactionStatus: String,
    val operationType: String,
    val occurredAt: String,
    val paidAt: String,
    val createdAt: String
)