package com.epy.linespotv2.domain.model.profile

data class JukirModel(
    val userId: Long = 0L,
    val nik: String = "",
    val fullName: String = "",
    val username: String = "",
    val email: String = "",
    val phone: String = "",
    val photoUrl: String = "",
    val isVerified: Boolean = false,
    val roleId: Long = 0L,
    val roleCode: String = "",
    val roleName: String = "",
    val saldo: Long = 0L,
    val lokasiId: Long = 0L,
    val lokasiCode: String = "",
    val lokasiName: String = "",
    val address: String = "",
    val minLatitude: Double = 0.0,
    val maxLatitude: Double = 0.0,
    val minLongitude: Double = 0.0,
    val maxLongitude: Double = 0.0,
    val centerLatitude: Double = 0.0,
    val centerLongitude: Double = 0.0,
    val radiusMeter: Long = 0L,
    val areaId: Long = 0L,
    val areaName: String = "",
    val zoneId: Long = 0L,
    val zoneName: String = "",
    val assignmentEffectiveFrom: String = "",
    val assignmentEffectiveTo: String = "",
    val todayIncome: Long = 0L,
    val totalIncome: Long = 0L,
    val todayTransactionCount: Long = 0L,
    val unreadNotificationCount: Long = 0L
)
